apiVersion: skaffold/v2alpha1
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: saschascata/multi-frontend
      context: ss-frontend
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer:
        - '***/*.js'
        - '***/*.css'
        - '***/*.html'
    - image: saschascata/multi-backend
      context: ss-backend
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer:
        - '**/*.js'
deploy:
  kubectl:
    manifests:
      - k8s/frontend-deployment.yaml
      - k8s/backend-deployment.yaml
      - k8s/backend-cluster-ip-service.yaml
      - k8s/frontend-cluster-ip-service.yaml